Styles shopping list
AlinaTantsura/project-twelve_team_JS pull request #15
Opened 2023-11-11 17:30 UTC by Siemtsov

Додано розмітку під картки, з книжками, в якості прикладу додано одну картку для перегляду

2023-11-11 18:54 UTC, AlinaTantsura requested changes
Передивись та видали загальні стилі. Кольори підключи через var, з бекграундом я розберусь, це в іншому файлі.

2023-11-11 18:54 UTC, AlinaTantsura commented on src/css/shopping-list.css
> +  .shopping-element {
@media only screen and (min-width: 768px)  Ось ця строка повторюється постійно. Я розумію чому, але можна згрупувати спочатку мобільні стилі, потім @media only screen and (min-width: 768px)  - прописати всі десктопні стилі, а потім @media only screen and (min-width: 1440px)  - це трохи скоротить код.

2023-11-11 18:54 UTC, AlinaTantsura commented on src/css/shopping-list.css
> +  background: #fff;
Додай кольори з загальних стилів background: var(--white);

2023-11-11 18:54 UTC, AlinaTantsura commented on src/css/shopping-list.css
> +  color: white;
Передивись всі кольори та підстав із загальних стилів - через var

2023-11-11 18:54 UTC, AlinaTantsura commented on src/css/shopping-list.css
> +  font-weight: 700;
Видали загальні стилі, наприклад (font-family: 'DM Sans', sans-serif) - передивись, font-style: normal; - також загальний стиль

2023-11-11 18:54 UTC, AlinaTantsura commented on src/css/shopping-list.css
> +  font-weight: 400;
Знову повторюються стилі загальні

2023-11-11 18:55 UTC, AlinaTantsura commented on src/css/shopping-list.css
> +  font-weight: 400;
Ще іконки не додані амазон та епл-бук(може це далі ти планував). Корзина не відображається також

2023-11-11 23:49 UTC, Siemtsov commented
Корекція помилок, додав стилі для заднбого фону, прописав js для відмальовки заднього фону

2023-11-12 09:17 UTC, AlinaTantsura approved these changes

2023-11-12 09:17 UTC, merged