header черновик
AlinaTantsura/project-twelve_team_JS pull request #8
Opened 2023-11-10 20:11 UTC by Olha-buz

2023-11-10 20:26 UTC, AlinaTantsura requested changes
Дивись, доробляй, щоб воно мало вигляд, як на макеті. Тоді скинеш.

2023-11-10 20:26 UTC, AlinaTantsura commented on src/css/header.css
>    padding: 20px 0;
Це можна видалити

2023-11-10 20:26 UTC, AlinaTantsura commented on src/partials/header.html
> +          <a href="../index.html" class="header-home">Home</a>
Дві крапочки прибери, залиш 1, а то може не працювати

2023-11-10 20:26 UTC, AlinaTantsura commented on src/partials/header.html
> +          <a href="../shopping.html" class="header-shoplist">
Теж крапочки

2023-11-10 20:26 UTC, AlinaTantsura commented on src/partials/header.html
> +    <!--Mobile-menu-header-->
Це ж частина для мобільного вікна. Залиш її Каті, вона тобі не потрібна. Можеш закоментувати тимчасово

2023-11-10 20:33 UTC, Olha-buz commented on src/partials/header.html
> +    <!--Mobile-menu-header-->
так, вже все підправляю)

2023-11-10 21:40 UTC, Olha-buz commented on src/css/header.css
>    padding: 20px 0;
виправила

2023-11-10 21:42 UTC, Olha-buz commented on src/partials/header.html
> +    <!--Mobile-menu-header-->
прибрала, вказала лише коммент де місце під модальне вікно

2023-11-11 07:49 UTC, AlinaTantsura approved these changes

2023-11-11 07:49 UTC, merged